CREATE TABLE IF NOT EXISTS profesores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre  VARCHAR(120) NOT NULL,
  curso   VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS evaluaciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  profesor_id INT NOT NULL,
  q1 TINYINT NOT NULL CHECK (q1 BETWEEN 1 AND 5),
  q2 TINYINT NOT NULL CHECK (q2 BETWEEN 1 AND 5),
  q3 TINYINT NOT NULL CHECK (q3 BETWEEN 1 AND 5),
  q4 TINYINT NOT NULL CHECK (q4 BETWEEN 1 AND 5),
  q5 TINYINT NOT NULL CHECK (q5 BETWEEN 1 AND 5),
  comentario TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_profesor
    FOREIGN KEY (profesor_id) REFERENCES profesores(id)
    ON DELETE CASCADE
);
